optimize etcd-endpoint-secret-generator-job
Signed-off-by: frezes <zhangjunhao@kubesphere.io>

diff --git a/charts/wiztelemetry-monitoring-helper/templates/etcd-endpoint-secret-generator-job.yaml b/charts/wiztelemetry-monitoring-helper/templates/etcd-endpoint-secret-generator-job.yaml
--- a/charts/wiztelemetry-monitoring-helper/templates/etcd-endpoint-secret-generator-job.yaml
+++ b/charts/wiztelemetry-monitoring-helper/templates/etcd-endpoint-secret-generator-job.yaml
@@ -1,5 +1,4 @@
-{{- if and .Values.etcdMonitoringHelper.enabled  .Values.etcdMonitoringHelper.etcdEndpointSecretGenerator.enabled -}}
-{{- if not (lookup "v1" "Endpoints" "kube-system" "whizard-monitoring-agent-k-kube-etcd") }}
+{{- if and .Values.etcdMonitoringHelper.enabled  .Values.etcdMonitoringHelper.etcdEndpointSecretGenerator.enabled }}
 apiVersion: v1
 kind: ConfigMap
 metadata:
@@ -8,23 +7,38 @@ metadata:
   labels:
     app: etcd-endpoint-secret-generator
   annotations:
-    "helm.sh/hook": pre-install,pre-upgrade
+    "helm.sh/hook": post-install,post-upgrade
     "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 data:
   etcd-endpoint-secret-generator.sh: |
     #!/bin/sh
-    
-    kubectl -n {{ template "wiztelemetry-monitoring-helper.namespace" . }} create secret generic kube-etcd-client-certs \
-            --from-file=etcd-client-ca.crt=/etc/ssl/etcd/ssl/ca.pem \
-            --from-file=etcd-client.crt=/etc/ssl/etcd/ssl/node-${KUBERNETES_NODE_NAME}.pem \
-            --from-file=etcd-client.key=/etc/ssl/etcd/ssl/node-${KUBERNETES_NODE_NAME}-key.pem
-    
-    cat <<EOF > etcd-endpoints.yaml
+
+    if kubectl get endpoints whizard-monitoring-agent-k-kube-etcd -n kube-system >/dev/null 2>&1; then
+        echo "Endpoint whizard-monitoring-agent-k-kube-etcd exists. Skip."
+    elif [ $? -eq 1 ]; then
+        kubectl -n {{ template "wiztelemetry-monitoring-helper.namespace" . }} create secret generic kube-etcd-client-certs \
+                --from-file=etcd-client-ca.crt=/etc/ssl/etcd/ssl/ca.pem \
+                --from-file=etcd-client.crt=/etc/ssl/etcd/ssl/node-${KUBERNETES_NODE_NAME}.pem \
+                --from-file=etcd-client.key=/etc/ssl/etcd/ssl/node-${KUBERNETES_NODE_NAME}-key.pem
+        
+        cat <<EOF > etcd-endpoints.yaml
     apiVersion: v1
     kind: Endpoints
     metadata:
+      annotations:
+        meta.helm.sh/release-name: whizard-monitoring-agent
+        meta.helm.sh/release-namespace: kubesphere-monitoring-system
       labels:
+        app: kube-prometheus-stack-kube-etcd
+        app.kubernetes.io/instance: whizard-monitoring-agent
+        app.kubernetes.io/managed-by: Helm
         app.kubernetes.io/name: etcd
+        app.kubernetes.io/part-of: kube-prometheus-stack
+        app.kubernetes.io/vendor: kubesphere
+        heritage: Helm
+        k8s-app: etcd-server
+        kubesphere.io/extension-ref: whizard-monitoring
+        release: whizard-monitoring-agent
       name: whizard-monitoring-agent-k-kube-etcd
       namespace: kube-system
     subsets:
@@ -34,18 +48,23 @@ data:
         protocol: TCP
       addresses:
     EOF
-    
-    # get etcd address from kube-apiserver and replace the etcd address in etcd-endpoints.yaml
-    etcdendpoints=$(kubectl get pod -n kube-system -l component=kube-apiserver -o jsonpath='{.items[0].spec.containers[0].command}' | jq -r '.[] | select(startswith("--etcd-servers="))' | grep -oE "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
-    
-    for ip in $etcdendpoints; do
-      echo "  - ip: $ip" >> etcd-endpoints.yaml
-    done
-    
-    kubectl apply -f etcd-endpoints.yaml
-    
+        
+        # get etcd address from kube-apiserver and replace the etcd address in etcd-endpoints.yaml
+        etcdendpoints=$(kubectl get pod -n kube-system -l component=kube-apiserver -o jsonpath='{.items[0].spec.containers[0].command}' | jq -r '.[] | select(startswith("--etcd-servers="))' | grep -oE "([0-9]{1,3}[\.]){3}[0-9]{1,3}")
+        
+        for ip in $etcdendpoints; do
+          echo "  - ip: $ip" >> etcd-endpoints.yaml
+        done
+        
+        kubectl apply -f etcd-endpoints.yaml
+    else
+        echo "Error checking Endpoint" >&2
+        exit 1
+    fi    
 
+{{- end }}
 ---
+{{- if and .Values.etcdMonitoringHelper.enabled  .Values.etcdMonitoringHelper.etcdEndpointSecretGenerator.enabled }}
 apiVersion: batch/v1
 kind: Job
 metadata:
@@ -54,7 +73,7 @@ metadata:
   labels:
     app: etcd-endpoint-secret-generator
   annotations:
-    "helm.sh/hook": pre-install,pre-upgrade
+    "helm.sh/hook": post-install,post-upgrade
     "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
 spec:
   backoffLimit: {{ .Values.hook.backoffLimit }}
@@ -137,5 +156,5 @@ spec:
           defaultMode: 420
           name: {{ printf "%s-%s" (include "wiztelemetry-monitoring-helper.fullname" .) "etcd-endpoint-secret-generator" | trunc 63 | trimSuffix "-" }}
         name: etcd-endpoint-secret-generator
-{{- end -}}
-{{- end -}}
+
+{{- end }}
